steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mackathon-team-c/face', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mackathon-team-c/face']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'face-recognition', '--image', 'gcr.io/mackathon-team-c/face', '--region', 'us-central1']
images:
- gcr.io/mackathon-team-c/face